# SpringBoot
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SaVa?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: savaer
    password: Sava@1951581
